### ISSUE TITLE
ETH balance display not updated 

### ISSUE THREAD

**Issue by schmidsi** [melonproject/faucet#10]
But ETH and MLN received

<img width="1552" alt="screen shot 2018-01-04 at 15 28 15" src="https://user-images.githubusercontent.com/103280/34568896-85aef7be-f167-11e7-891e-1f8c4982daf6.png">

**Comment by ferranbt** [comment]
Confirmed. It seems that faucet backend web3 confirms the transactions when it still pending. Then when the frontend checks the balance it is still zero since the transaction has not been mined. It should happen also with the melon token balance.
