### ISSUE TITLE
Consume user address via URL param & Input field

### ISSUE THREAD

**Issue by schmidsi** [melonproject/faucet#7]
In the new IPFS-frontend, we don't rely on MetaMask anymore. We will do account management in the browser with ethers.js.

In order to have to faucet still working, it needs to send MLN/ETH to the address that is provided via URL.

We will create a link to the faucet with the address of the user coded in:
faucet.melon.network/to/0xDEADBEEF (or via ?address=0xDEADBEEF, what ever is easier to implement)

Furthermore, it would help to have a input box displaying the target address. If none is provided via URL, the user is free to fill in any address.

Remove MetaMask dependency completely. (Or maybe not?)

**Comment by retotrinkler** [comment]
thx @schmidsi 
should be _faucet.melon.**fund**/.._

**Comment by schmidsi** [comment]
Thanks @ferranbt
