### ISSUE TITLE
Faucet says I already requested ether when this is not true.

### ISSUE THREAD

**Issue by nmortil** [melonproject/faucet#8]
I tried requesting kovan ether and melon but after clicking request it says that I have already requested more than once in a 24 hour period. I have waited more than 24 hours and tried again and keep on getting the same message.

**Comment by schmidsi** [comment]
Thanks for the report. We are working on our abuse-prevention algorithms. In the meantime, feel free to ask on our Gitter (https://gitter.im/melonproject/general) for more K-ETH and K-MLN.

**Comment by schmidsi** [comment]
@nmortil We just released a new version. Can you try again? Now with SSL: https://faucet.melon.network/

**Comment by nmortil** [comment]
Tried it and it works now, but only got K-MLN no K-ETH.
